const employees = [
  {
    id: 1,
    firstname: "Aarav",
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Complete the project documentation.",
        date: "2025-01-01",
        category: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Fix bugs in the login module.",
        date: "2025-01-02",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Test the payment gateway integration.",
        date: "2025-01-03",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstname: "Ishita",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Design wireframes for the new feature.",
        date: "2025-01-04",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Optimize the database queries.",
        date: "2025-01-05",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Respond to customer queries.",
        date: "2025-01-06",
        category: "Support",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Prepare the testing report.",
        date: "2025-01-07",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
  },
  {
    id: 3,
    firstname: "Vikram",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Review the API documentation.",
        date: "2025-01-08",
        category: "Documentation",
        active: false,
        newTask: true,
        completed: false,
        failed: true,
      },
      {
        title: "Task 2",
        description: "Develop a new feature for the admin panel.",
        date: "2025-01-09",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Conduct UI testing.",
        date: "2025-01-10",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Help team members with debugging.",
        date: "2025-01-11",
        category: "Support",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Update the user guide.",
        date: "2025-01-12",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 2,
      failed: 1,
    },
  },
  {
    id: 4,
    firstname: "Meera",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Finalize the design for the home page.",
        date: "2025-01-13",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Monitor the production server logs.",
        date: "2025-01-14",
        category: "Support",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Prepare the quarterly report.",
        date: "2025-01-15",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskSummary: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 5,
    firstname: "Rohit",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "Task 1",
        description: "Implement caching for faster load times.",
        date: "2025-01-16",
        category: "Development",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Task 2",
        description: "Test the new email notification system.",
        date: "2025-01-17",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 3",
        description: "Update the mobile app design.",
        date: "2025-01-18",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Task 4",
        description: "Provide support to users reporting issues.",
        date: "2025-01-19",
        category: "Support",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Task 5",
        description: "Write a blog post about the latest release.",
        date: "2025-01-20",
        category: "Documentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
    taskSummary: {
      active: 3,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

const setLocalStorage = ()=>{
  localStorage.setItem('employees', JSON.stringify(employees));
  localStorage.setItem('admin', JSON.stringify(admin));
}

const getLocalStorage = ()=>{
  const employees = JSON.parse(localStorage.getItem('employees'));
  const admin = JSON.parse(localStorage.getItem('admin'));
  return {employees, admin};
}

export {setLocalStorage, getLocalStorage}